'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, House, Layers3, BriefcaseBusiness, UserRound, Mail, GitFork, Command as CommandIcon, Sun, Moon, MapPin, Code2, Cpu, Copy, Check, Terminal, Puzzle, Monitor, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from '@/components/ui/command';

type View = 'overview' | 'projects' | 'experience' | 'about';
type Filter = 'All projects' | 'Web apps' | 'Systems' | 'Salesforce';
type Project = { id: string; title: string; category: Filter; type: string; year: string; image?: string; tone: string; description: string; details: string; features: string[]; stack: string[]; source: string; live?: string; credit?: string };
const email = 'ajaykareer06@gmail.com';
const nav = [{ id: 'overview', name: 'Overview', icon: House }, { id: 'projects', name: 'Projects', icon: Layers3 }, { id: 'experience', name: 'Experience', icon: BriefcaseBusiness }, { id: 'about', name: 'About me', icon: UserRound }] as const;
const projects: Project[] = [
 { id:'windows-update-manager', title:'Windows Update Manager', category:'Systems', type:'WINDOWS UTILITY', year:'2025', image:'windows-update-manager.png', tone:'systems', description:'Practical control over Windows updates for POS terminals, kiosks, and PCs.', details:'A menu-driven Windows utility that brings update controls, restoration, and status checks into one place. Built for situations where operating-system maintenance needs deliberate timing.', features:['Menu-based controls for blocking and restoring updates','Windows service and policy status checks','Scheduled watchdog tasks for maintaining the chosen configuration'], stack:['Windows Batch','PowerShell','Windows services'], source:'https://github.com/ajaykareer/Windows-Update-Manager' },
 { id:'weather-app', title:'The Weather App', category:'Web apps', type:'WEB APPLICATION', year:'2023', image:'weather-69c3ec64.jpg', tone:'weather', description:'A simple way to check the weather in cities around the world.', details:'A weather interface that uses a weather API to turn a city search into readable conditions. An exploration of API integration and responsive front-end development.', features:['City-based weather lookup','Current conditions from a weather API','Responsive interface for different screen sizes'], stack:['JavaScript','Bootstrap','CSS','Weather API'], source:'https://github.com/ajaykareer/WeatherAPP', live:'https://weather-app-ten-lemon.vercel.app' },
 { id:'word-shuffle', title:'Word Shuffle', category:'Salesforce', type:'SALESFORCE APPLICATION', year:'2024', tone:'salesforce', description:'A word game built inside Salesforce, with difficulty levels and saved results.', details:'A Salesforce game built with Aura components and Apex. Players pick a difficulty, rearrange letters, and try to find the target word within three attempts. Results are stored for each user.', features:['Three difficulty levels and a reshuffle action','Three attempts with in-game feedback','Per-user game results stored through Apex and SOQL'], stack:['Salesforce Aura','Apex','JavaScript','SOQL'], source:'https://github.com/ajaykareer/Word-Shuffle-Game-Salesforce-Aura' },
 { id:'web-gallery', title:'AKK Web Gallery', category:'Web apps', type:'PHOTO GALLERY', year:'2023', image:'akk-9a32c0fd.jpg', tone:'gallery', description:'A photo gallery with account registration, built with React and Firebase.', details:'A web-gallery project that explores an account-based photo experience and Firebase integration through a React interface.', features:['Photo gallery browsing','Account registration','React interface with Firebase integration'], stack:['React','Firebase','CSS'], source:'https://github.com/ajaykareer/web-gallery', live:'https://akk-web-gallery.web.app/', credit:'Adapted from Diego Arndt’s web-gallery project. The public repository is a fork.' },
 { id:'davosbet', title:'DavosBet', category:'Web apps', type:'SPORTS INTERFACE', year:'2023', image:'davosbet-2ba74307.jpg', tone:'sports', description:'A sports interface exploring live scores, standings, and sports data.', details:'A sports-data front end that brings scores and standings into a dashboard. This project explores working with an external sports API and responsive interface styling.', features:['Sports scores and standings','External sports API integration','Responsive layout and navigation'], stack:['JavaScript','Tailwind CSS','SCSS','Sports API'], source:'https://github.com/ajaykareer/davosbet/', credit:'Adapted from Diego Arndt’s DavosBet project. The public repository is a fork.' },
];

function ProjectCard({ project, index, onOpen }: { project: Project; index: number; onOpen: (project: Project) => void }) {
 return <article className="project-card"><button className="project-card-button" onClick={() => onOpen(project)} aria-label={`View ${project.title}`}><div className={`project-visual tone-${project.tone}`}>
 {project.image ? <img src={`/projects/${project.image}`} alt={`${project.title} interface`} loading="lazy" width="1000" height="600"/> : <div className="word-project"><Puzzle size={32}/><span className="word-tiles" aria-hidden="true">{'SHUFFLE'.split('').map((letter,i)=><span key={i}>{letter}</span>)}</span><span className="word-caption">A LITTLE PLAY. A LITTLE APEX.</span></div>}
 <span className="project-open"><ArrowUpRight/></span></div><div className="project-heading"><div><p className="eyebrow">{project.type}</p><h3>{project.title}</h3></div><span className="project-number">0{index+1}</span></div></button><p className="project-description">{project.description}</p><div className="tags">{project.stack.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div></article>;
}

export default function Portfolio() {
 const [view,setView] = useState<View>('overview');
 const [filter,setFilter] = useState<Filter>('All projects');
 const [selected,setSelected] = useState<Project | null>(null);
 const [commandOpen,setCommandOpen] = useState(false);
 const [contactOpen,setContactOpen] = useState(false);
 const [dark,setDark] = useState(false);
 const [copyState,setCopyState] = useState<'idle'|'copied'|'failed'>('idle');
 const pageHeading = useRef<HTMLHeadingElement>(null);
 const didMount = useRef(false);
 const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

 useEffect(() => {
  const syncHash = () => { const value = window.location.hash.slice(1); if(nav.some(item=>item.id===value)) setView(value as View); else setView('overview'); };
  syncHash(); window.addEventListener('hashchange',syncHash);
  try { const stored = localStorage.getItem('ajay-portfolio-theme'); setDark(stored ? stored==='dark' : window.matchMedia('(prefers-color-scheme: dark)').matches); } catch { /* Theme remains usable when storage is unavailable. */ }
  return () => { window.removeEventListener('hashchange',syncHash); if(copyTimer.current) clearTimeout(copyTimer.current); };
 },[]);
 useEffect(()=>{ document.documentElement.classList.toggle('dark',dark); },[dark]);
 useEffect(()=>{
  if(didMount.current) { window.scrollTo({top:0,behavior:'instant'}); pageHeading.current?.focus({preventScroll:true}); }
  didMount.current=true;
 },[view]);
 useEffect(()=>{ const key=(event:KeyboardEvent)=>{ if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault(); setSelected(null);setContactOpen(false);setCommandOpen(open=>!open);} };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key); },[]);
 const navigate = useCallback((next:View)=>{setView(next);setCommandOpen(false);window.location.hash=next;},[]);
 const toggleTheme = () => {setDark(value=>{const next=!value;try{localStorage.setItem('ajay-portfolio-theme',next?'dark':'light');}catch{}return next;});};
 const openProject = (project:Project) => {setCommandOpen(false);setSelected(project);};
 const openContact = () => {setCommandOpen(false);setCopyState('idle');setContactOpen(true);};
 const copyEmail = async () => {try{await navigator.clipboard.writeText(email);setCopyState('copied');}catch{setCopyState('failed');}if(copyTimer.current)clearTimeout(copyTimer.current);copyTimer.current=setTimeout(()=>setCopyState('idle'),4000);};
 const currentTitle=nav.find(item=>item.id===view)?.name;
 const visibleProjects=projects.filter(project=>filter==='All projects'||project.category===filter);

 return <div className="portfolio-app"><a className="skip-link" href="#main">Skip to content</a>
  <aside className="sidebar"><a className="monogram" href="#overview" aria-label="Ajay Kareer home" onClick={()=>navigate('overview')}>ak<span aria-hidden="true">✳</span></a><div className="sidebar-identity"><h2>Ajay Kareer</h2><p>Software & hardware engineer</p></div><p className="nav-label">EXPLORE</p><nav aria-label="Portfolio">{nav.map(({id,name,icon:Icon},i)=><Button variant="ghost" className={`nav-item ${view===id?'active':''}`} key={id} aria-label={name} aria-current={view===id?'page':undefined} onClick={()=>navigate(id)} title={name}><Icon/><span className="nav-name">{name}</span><span className="nav-number">0{i+1}</span></Button>)}</nav><div className="sidebar-bottom"><p>HAVE SOMETHING IN MIND?</p><Button variant="ghost" className="say-hello" onClick={openContact}>Let’s talk <ArrowUpRight/></Button><div className="social-links"><a href="https://github.com/ajaykareer" aria-label="GitHub" target="_blank" rel="noopener noreferrer"><GitFork/></a><a href="https://linkedin.com/in/ajaykareer" aria-label="LinkedIn" target="_blank" rel="noopener noreferrer"><span className="linkedin-mark">in</span></a><a href={`mailto:${email}`} aria-label="Email Ajay"><Mail/></a></div></div></aside>
  <div className="main-shell"><header className="topbar"><div><span className="breadcrumb-muted">Portfolio</span><span className="breadcrumb-slash">/</span>{currentTitle}</div><div className="top-actions"><Button variant="ghost" className="command-button" onClick={()=>setCommandOpen(true)} aria-label="Quick jump, Control or Command K"><CommandIcon size={15}/><span>Quick jump</span><kbd>Ctrl K</kbd></Button><span className="top-divider"/><Button variant="ghost" size="icon" className="theme-button" onClick={toggleTheme} aria-label={`Switch to ${dark?'light':'dark'} theme`} title={`Switch to ${dark?'light':'dark'} theme`}>{dark?<Sun/>:<Moon/>}</Button></div></header>
  <main id="main" className="content" tabIndex={-1}><div className="page-view" key={view}>
   {view==='overview' && <><section className="intro"><div className="intro-copy"><p className="eyebrow"><span className="small-spark" aria-hidden="true">✳</span> HELLO, I’M AJAY</p><h1 ref={pageHeading} tabIndex={-1}>Software meets<br/>the <em>real world.</em></h1><p className="intro-description">I connect the dots between thoughtful software and hands-on hardware. Currently building at <strong>CreativePOS.</strong></p><div className="hero-actions"><Button className="primary-action" onClick={()=>navigate('projects')}>Explore my projects <ArrowUpRight/></Button><Button variant="ghost" className="text-action" onClick={openContact}>Get in touch <ArrowRight size={16}/></Button></div><div className="location"><MapPin size={14}/> Toronto, Canada <span>·</span> Always curious. Always building.</div></div><div className="portrait-wrap"><div className="portrait-frame"><img src="/projects/myself-f578b1ab.png" alt="Ajay Kareer smiling" width="1500" height="2000"/><span className="portrait-caption">THE PERSON BEHIND THE PIXELS</span></div><div className="portrait-sticker"><Code2/><span>Code.<br/>Connect.<br/>Create.</span></div><span className="photo-mark" aria-hidden="true">✳</span></div></section>
   <button className="current-role" onClick={()=>navigate('experience')}><span className="role-icon"><Cpu/></span><span className="role-copy"><span className="eyebrow">WHERE I AM NOW</span><span className="role-title">Software & Hardware Engineer <span>@ CreativePOS</span></span></span><span className="role-date">JUN 2024 — PRESENT</span><ArrowUpRight className="role-arrow"/></button>
   <section className="selected-work"><div className="section-title"><div><span className="eyebrow">A FEW THINGS I’VE WORKED ON</span><h2>Selected projects<span> / {String(projects.length).padStart(2,'0')}</span></h2></div><Button variant="ghost" onClick={()=>navigate('projects')}>View all projects <ArrowRight size={16}/></Button></div><div className="project-grid">{projects.slice(0,2).map((project,index)=><ProjectCard key={project.id} project={project} index={index} onOpen={openProject}/>)}</div></section></>}

   {view==='projects' && <><div className="view-heading"><p className="eyebrow">SELECTED WORK / 2023 — 2025</p><h1 ref={pageHeading} tabIndex={-1}>Curiosity, <em>in practice.</em></h1><p>Web experiences, useful tools, and experiments along the way.</p></div><div className="filter-bar"><div className="filter-buttons" aria-label="Filter projects">{(['All projects','Web apps','Systems','Salesforce'] as Filter[]).map(item=><Button variant="ghost" key={item} onClick={()=>setFilter(item)} aria-pressed={filter===item} className={`filter-button ${filter===item?'is-active':''}`}>{item}</Button>)}</div><span className="results-count" role="status">{visibleProjects.length} {visibleProjects.length===1?'project':'projects'}</span></div><div className="project-grid full-project-grid">{visibleProjects.map(project=><ProjectCard key={project.id} project={project} index={projects.indexOf(project)} onOpen={openProject}/>)}</div></>}

   {view==='experience' && <><div className="view-heading"><p className="eyebrow">THE JOURNEY SO FAR</p><h1 ref={pageHeading} tabIndex={-1}>Code is only<br/><em>half the story.</em></h1><p>Working where software, hardware, and everyday use come together.</p></div><section className="experience-card"><div className="experience-top"><span className="large-icon"><Cpu/></span><div><span className="current-badge">CURRENT ROLE</span><h2>CreativePOS</h2><p>Software & Hardware Engineer</p></div></div><div className="experience-date"><CalendarDays size={17}/><time dateTime="2024-06-01">June 1, 2024</time><span>— Present</span></div><p className="experience-description">Since June 2024, I’ve been working as a Software & Hardware Engineer at CreativePOS. My focus brings together two sides of technology: the software people interact with and the hardware it runs on.</p><div className="practice-grid"><div><Code2/><h3>Software</h3><p>Thinking through how an application works, from its interface to the logic behind it.</p></div><div><Monitor/><h3>Hardware</h3><p>Bringing a hands-on engineering perspective to the devices behind the experience.</p></div><div><Cpu/><h3>Point of sale</h3><p>Working in the space where digital systems meet everyday business operations.</p></div></div></section><section className="related-work"><p className="eyebrow">FROM MY PERSONAL TOOLBOX</p><h2>A practical systems project</h2><button className="related-project" onClick={()=>openProject(projects[0])}><Terminal/><span><strong>Windows Update Manager</strong><span>A personal utility for Windows terminals, kiosks, and PCs.</span></span><ArrowUpRight/></button></section></>}

   {view==='about' && <><div className="view-heading"><p className="eyebrow">MORE THAN A JOB TITLE</p><h1 ref={pageHeading} tabIndex={-1}>A builder.<br/>A <em>curious mind.</em></h1></div><section className="about-grid"><div className="about-photo"><img src="/projects/myself-f578b1ab.png" alt="Ajay Kareer" width="1500" height="2000"/><span>AJAY KAREER / TORONTO, CANADA</span></div><div className="about-copy"><h2>Hi, I’m Ajay.</h2><p>I’m a software and hardware engineer based in Toronto. I started with websites and web applications, and my work now extends into the hands-on world of hardware and point-of-sale systems at CreativePOS.</p><p>I like the space between an idea and something you can actually use. Sometimes that’s a weather app. Sometimes it’s a Salesforce game. Sometimes it’s a Windows utility that makes a practical task more manageable.</p><p>This is a collection of those explorations—and a little of the person behind them.</p><Button className="primary-action" onClick={openContact}>Say hello <ArrowUpRight/></Button></div></section><section className="toolbox"><div className="section-title"><div><p className="eyebrow">TOOLS I’VE WORKED WITH</p><h2>Different tools. Same curiosity.</h2></div><Code2/></div><div className="toolbox-grid"><div><h3>Web development</h3><div className="tags">{['JavaScript','React','HTML & CSS','Tailwind CSS','Bootstrap','Firebase'].map(item=><span key={item}>{item}</span>)}</div></div><div><h3>Systems & platforms</h3><div className="tags">{['Windows Batch','PowerShell','Salesforce Aura','Apex','SOQL'].map(item=><span key={item}>{item}</span>)}</div></div></div></section></>}
  </div><footer className="page-footer"><span>© {new Date().getFullYear()} Ajay Kareer</span><button onClick={openContact}>Let’s make something useful. <span className="orange" aria-hidden="true">✳</span></button></footer></main></div>

  <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="project-dialog">{selected&&<><DialogHeader><p className="eyebrow">{selected.type} / {selected.year}</p><DialogTitle className="dialog-title">{selected.title}</DialogTitle><DialogDescription className="dialog-description">{selected.description}</DialogDescription></DialogHeader>{selected.image&&<div className={`dialog-image tone-${selected.tone}`}><img src={`/projects/${selected.image}`} alt={`${selected.title} screenshot`}/></div>}<p className="project-detail-text">{selected.details}</p><h3 className="detail-heading">What’s inside</h3><ul className="feature-list">{selected.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><div className="tags">{selected.stack.map(tag=><span key={tag}>{tag}</span>)}</div>{selected.credit&&<p className="project-credit">{selected.credit}</p>}<div className="dialog-actions"><a className="external-action" href={selected.source} target="_blank" rel="noopener noreferrer"><GitFork size={17}/> View source <ArrowUpRight size={16}/></a>{selected.live&&<a className="external-action accent-action" href={selected.live} target="_blank" rel="noopener noreferrer">Open live project <ArrowUpRight size={16}/></a>}</div></>}</DialogContent></Dialog>
  <Dialog open={commandOpen} onOpenChange={setCommandOpen}><DialogContent className="command-dialog"><DialogHeader className="sr-only"><DialogTitle>Quick jump</DialogTitle><DialogDescription>Search pages and projects. Use the arrow keys and Enter to choose.</DialogDescription></DialogHeader><Command><CommandInput placeholder="Where would you like to go?" aria-label="Search pages and projects"/><CommandList><CommandEmpty>No matches. Try a project name or “about”.</CommandEmpty><CommandGroup heading="Explore">{nav.map(({id,name,icon:Icon})=><CommandItem key={id} onSelect={()=>navigate(id)}><Icon/>{name}</CommandItem>)}</CommandGroup><CommandGroup heading="Projects">{projects.map(project=><CommandItem key={project.id} onSelect={()=>openProject(project)}><Layers3/>{project.title}</CommandItem>)}</CommandGroup><CommandGroup heading="Connect"><CommandItem onSelect={openContact}><Mail/>Get in touch</CommandItem></CommandGroup></CommandList><div className="command-hint"><span>↑ ↓ to navigate · Enter to open</span><span>Esc to close</span></div></Command></DialogContent></Dialog>
  <Dialog open={contactOpen} onOpenChange={setContactOpen}><DialogContent className="contact-dialog"><DialogHeader><span className="contact-spark" aria-hidden="true">✳</span><p className="eyebrow">GOOD THINGS START WITH A CONVERSATION</p><DialogTitle className="dialog-title">Let’s connect.</DialogTitle><DialogDescription className="dialog-description">Have an idea, a question, or just want to say hello? My inbox is a good place to start.</DialogDescription></DialogHeader><div className="email-row"><a href={`mailto:${email}`}>{email}</a><Button variant="ghost" size="icon" aria-label="Copy email address" onClick={copyEmail}>{copyState==='copied'?<Check/>:<Copy/>}</Button></div><p className="copy-status" role="status">{copyState==='copied'?'Email address copied.':copyState==='failed'?'Copy is unavailable. Select the address above or use Open email.':''}</p><a className="external-action accent-action" href={`mailto:${email}`}><Mail size={17}/> Open email <ArrowUpRight size={17}/></a><div className="contact-social"><a href="https://github.com/ajaykareer" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={16}/></a><a href="https://linkedin.com/in/ajaykareer" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={16}/></a></div></DialogContent></Dialog>
 </div>;
}

